### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#31]
I get mixed results when searching for volume 1334. If I search using John Hafner or Ray Hilborn - (whom I noticed has a typo) I get the volume. But if I search using David Hafner, the volume doesn't come up. That's strange to me because I can see in AT that David is the primary name at the head of the volume.

Similar problem with volume 1499. You can only find it by searching with Alden Miller.

**Comment by jdeck88** [comment]
There are two issues here.  

The David Hafner result was getting dropped because his name was coming through as "Hafner, David, J."  The second comma was acting as a delimiter and his givenName was shortened to "David" and should have been "David, J.".  I fixed this issue by allowing any number of commas in the given name.  God help us if someone has a comma in their family name!    This is now fixed and you can search properly on this now.

The Alden Miller, volume 1499 problem stems from the fact that there are multiple authors per section.  The database only stores one section author.  Volumes can have multiple authors but only by virtue of the fact that there are multiple sections, each having its own author.   

I'm going to close this particular issue since #1 was a bug, but if you DO require the ability to search on multiple SECTION authors, create a new issue.

**Comment by mkoo** [comment]
I think this is fine (at least for now). A search for any author in a multi-authored section will give you results so that's the important factor.

**Comment by cfidler** [comment]
There are other volumes with multiple authors within a given section. I am working on right now (Cosgriff and Leffler). How should I handle these? This may be a future problem because I know that some GRP sections are mixed. Should I drop the second author for now? In the current Cosgriff case, neither author is in any other part of the volume. So if I dropped Leffler, and you searched for him, it would not bring up this volume.

**Comment by mkoo** [comment]
Am I misreading how this is working then? When I search for Hafner, David, I get this:
Field Notes: Hafner D.J. 1973-74, J.C. Hafner 1969-72, R. Hillborn 1969, v1334

Each section is a different author. And if I search on any of their names I get the same result.

So this is the case of each section have more than one author, right? So those names will be in the section title, and perhaps some help text or automatically searching in section title along with named author allow one to discover sections wtih that name in it?

**Comment by jdeck88** [comment]
The Hafner example works because you'll notice that each of the three authors listed in the volume is the primary author of at least one section in the volume.  So, the issue only arises when there is more than one author of a section, and the secondary author has not authored any other sections in the volume.  For now, i would continue to list the secondary, tertiary authors of sections, even if we can't search on them right now.  At some point, i can modify the database to store multiple authors on each section and query across all of them...   So-- if this is desired, you can go ahead and open a new issue for this feature.
