### ISSUE TITLE
Not all sections showing up

### ISSUE THREAD

**Issue by cfidler** [BNHM/ecoreader#9]
Hi John - I looked up Borrell, Adrey E. and I noticed that the sections appear to be missing (e.g. v540). I just looked up the MODS file and they are all marked up in the file. I don't know if this is happening to other files.

Thanks,
Christina

**Comment by mkoo** [comment]
I believe other authors also have mssing sections and volumes.

EG: Alexander, annie
missing or incomplete records for v,493 - 500, v679, v1485

in addition some are missing the volume info so incomplete MODS retrieval?

**Comment by jdeck88** [comment]
I believe this bug is fixed.... there were some issues with the UPDATE function when new data was being updated, it wasn't being processed correctly.  I fixed that bug and started a job to scan through all MODS files again and i see all of the sections appearing that you mentioned missing.  I'm going to close this issue now but will add a new issue to VERIFY all volumes/sections/pages in the database independently.

**Comment by cfidler** [comment]
Sorry to revive this. It looks like the sections are showing up in reverse order. Can we have them start from 0?

**Comment by jdeck88** [comment]
Thats a new issue, i'll open it another issue thread

**Comment by mkoo** [comment]
looks good now!
